### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by kratman** [kratman/FLUKE_QMMM#17]
List of LICHEM features which are a work in progress:
- [ ] Theoretical background information has to be provided for all methods in LICHEM
- [ ] The NPT PIMC calculations do not appear to be giving correct densities and structures
- [ ] QMMM with diffuse charge density and the Gaussian Electrostatic Model (GEM) needs to be completed and released
- [ ] The Monte Carlo routines need to be more thoroughly tested. These include classical Monte Carlo (NVT/NPT), PIMC (NVT/NPT), and force-bias Monte Carlo (NVT)
- [ ] The LAMMPS wrapper needs to be completed and tested
- [ ] The reaction pathway routines need to be publicly released
